name: whatsapp_clone
description: "WhatsApp Clone - A Flutter messaging app with real-time features"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Backend Integration
  supabase_flutter: ^2.0.2
  
  # Configuration
  flutter_dotenv: ^5.1.0
  
  # Real-time Communication
  livekit_client: ^2.5.0
  
  # UI Framework
  flutter_chat_ui: ^1.6.9
  
  # Navigation
  go_router: ^12.1.3
  
  # Media Handling
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  image: ^4.1.7
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.1
  mime: ^1.0.4
  
  # File Compression
  flutter_image_compress: ^2.1.0
  video_compress: ^3.1.2
  
  # Permissions
  permission_handler: ^11.0.1
  
  # Utilities
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  
  # Security
  flutter_secure_storage: ^9.0.0
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  
  # Testing
  mocktail: ^1.0.0
  integration_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
