apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-clone-web
spec:
  replicas: 10
  template:
    spec:
      containers:
      - name: web
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: REGION
          value: "ap-southeast-1"
        - name: ENABLE_PERFORMANCE_MONITORING
          value: "true"
        - name: ENABLE_CRASH_REPORTING
          value: "true"
        - name: LOG_LEVEL
          value: "warn"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3